name: build

on:
  push:
    branches:
    - main
  pull_request: { }

defaults:
  run:
    shell: bash

jobs:
  build:
    if: ${{
      (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/'))
      || (github.event_name == 'push' && !startsWith(github.event.head_commit.message, '[push-back]'))
      || github.event_name != 'push'
      }}
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    concurrency: build-${{github.ref}}

    steps:
    - name: Checkout repository
      uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      with:
        submodules: recursive
        lfs: true
        fetch-depth: 1


    - name: Read action's Node.js version
      id: readNodeVersion
      run: |
        USING=$( yq .runs.using ./action.yml )
        if ! [[ "$USING" =~ ^node[0-9]+$ ]]; then
          echo "::error::action.yml: .runs.using doesn't start with 'node': '$USING'"
          exit 1
        fi
        VERSION=${USING:4}
        echo "Action's Node.js version: $VERSION"
        echo "result=$VERSION" >> $GITHUB_OUTPUT

    - name: Setup Node.js ${{steps.readNodeVersion.outputs.result}}
      uses: actions/setup-node@v3
      with:
        node-version: '${{steps.readNodeVersion.outputs.result}}'

    - name: Update Node.js version in project files
      run: |
        node update-node-version-in-files "${{steps.readNodeVersion.outputs.result}}"


    - name: Restore node_modules cache
      id: restore-node_modules-cache
      uses: actions/cache/restore@v3
      with:
        key: ${{runner.os}}-node_modules-${{hashFiles('package.json', 'yarn.lock', '.yarnrc.yml', '.yarn/patches/**', '.yarn/plugins/**', '.yarn/releases/**', '.yarn/versions/**')}}
        path: |
          node_modules

    - name: Install dependencies
      if: steps.restore-node_modules-cache.outputs.cache-hit != 'true'
      run: |
        yarn install --no-immutable

    - name: Save node_modules cache
      if: steps.restore-node_modules-cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v3
      with:
        key: ${{runner.os}}-node_modules-${{hashFiles('package.json', 'yarn.lock', '.yarnrc.yml', '.yarn/patches/**', '.yarn/plugins/**', '.yarn/releases/**', '.yarn/versions/**')}}
        path: |
          node_modules


    - name: Build
      run: |
        npm run build


    # $$$sync-with-template-modifiable: validation $$$

    - name: Run current action
      id: current
      uses: ./

    - name: Print result
      env:
        RESULT: ${{toJSON(fromJSON(steps.current.outputs.result))}}
      run: |
        echo "$RESULT"

    - name: Validate current action
      env:
        FULL_NAME: ${{fromJSON(steps.current.outputs.result).fullName}}
        OWNER_LOGIN: ${{fromJSON(steps.current.outputs.result).owner.login}}
        OWNER_NAME: ${{fromJSON(steps.current.outputs.result).owner.name}}
        OWNER_IS_USER: ${{fromJSON(steps.current.outputs.result).owner.isUser}}
        OWNER_IS_ORGANIZATION: ${{fromJSON(steps.current.outputs.result).owner.isOrganization}}
        LICENSE_DESCRIPTION: ${{fromJSON(steps.current.outputs.result).license.description}}
        IS_TEMPLATE: ${{fromJSON(steps.current.outputs.result).isTemplate}}
      run: |
        if [ "$FULL_NAME" != "${{github.repository}}" ]; then
          echo "::error::Repository full name '$FULL_NAME' doesn't equal to expected '${{github.repository}}'"
          exit 1
        fi
        if [ "$OWNER_LOGIN" != "${{github.repository_owner}}" ]; then
          echo "::error::Repository owner '$OWNER_LOGIN' doesn't equal to expected '${{github.repository_owner}}'"
          exit 1
        fi
        if [ "$OWNER_NAME" == "" ]; then
          echo "::error::Repository owner name is not set or empty"
          exit 1
        fi
        if [ "$OWNER_IS_USER" != "" ]; then
          echo "::error::Repository owner isUser is not empty"
          exit 1
        fi
        if [ "$OWNER_IS_ORGANIZATION" != "true" ]; then
          echo "::error::Repository owner isOrganization does't equal to true"
          exit 1
        fi
        if [ "$LICENSE_DESCRIPTION" == "" ]; then
          echo "::error::Repository license description is not set or empty"
          exit 1
        fi
        if [ "$IS_TEMPLATE" != "false" ]; then
          echo "::error::Repository isTemplate does't equal to false"
          exit 1
        fi

    # $$$sync-with-template-modifiable-end$$$


    - name: Push back
      env:
        PUSH_BACK_TOKEN: ${{secrets.PUSH_BACK_TOKEN}}
      if: ${{github.event_name == 'push' && startsWith(github.ref, 'refs/heads/') && env.PUSH_BACK_TOKEN}}
      uses: remal-github-actions/push-back@v1
      with:
        githubToken: ${{env.PUSH_BACK_TOKEN}}
        message: '[push-back] Push-back updated files during build'


    - name: Read version
      id: readVersion
      if: ${{github.event_name == 'push' && github.ref == 'refs/heads/main'}}
      uses: remal-github-actions/read-nodejs-package-version@v1

    - name: Create tag
      env:
        PUSH_BACK_TOKEN: ${{secrets.PUSH_BACK_TOKEN}}
      if: ${{github.event_name == 'push' && github.ref == 'refs/heads/main' && env.PUSH_BACK_TOKEN}}
      uses: remal-github-actions/create-tag@v1
      with:
        githubToken: ${{env.PUSH_BACK_TOKEN}}
        tagName: 'v${{steps.readVersion.outputs.majorVersion}}'
        forcePush: 'true'
